### ISSUE TITLE
Custom Effect API

### ISSUE THREAD

**Issue by GitWither** [leoste/video-scissors#25]
The custom effect API will allow users to:

- [x] Listen and react to events fired by the program

- [x] Add complex custom effects to modify videos

- [x] An API to register/modify user settings

**Comment by GitWither** [comment]
Introduced just the basics of this, will have to update when the program gets more functionality cough cough @leoste

**Comment by GitWither** [comment]
For now this is done, I will open a separate issue later in case new parts of the API are needed

**Comment by leoste** [comment]
🤘
