### ISSUE TITLE
Make classes internal so effects can't access them

### ISSUE THREAD

**Issue by GitWither** [leoste/video-scissors#31]
Classes that need to be internal:
- [ ] ButtonController
- [ ] CursorController
- [ ] FancyScrollbar
- [ ] IChildController
- [ ] IControlController
- [ ] IController
- [ ] IDraggableController
- [ ] IFrameController
- [ ] ILockableController
- [ ] IResizableController
- [ ] LayerController
- [ ] SliceController
- [ ] TimelineController
- [ ] ScrollDirection
- [ ] RulerController

**Comment by leoste** [comment]
won't actually make effects not able to access them but this is good for other things so i will do it still

**Comment by leoste** [comment]
you've got it backwards, effectsapi already can't access them because they are private although they don't implicitly have the modifier in code. you instead should make stuff in effectsapi private aswell
